name: API build Publish Docker image

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the FastAPI Docker image
      run: docker build -t '${{secrets.DOCKER_USERNAME}}'/legal_assist_api:'${{github.sha}}' .
      
    - name: Login to docker
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.DOCKER_USERNAME}}'/legal_assist_api:'${{github.sha}}'
